// Mock Brand and Campaign Data

import { Brand, Campaign } from './types';

export const mockBrands: Brand[] = [
  {
    id: 'brand-1',
    name: 'TechFlow Inc',
    logo: '💻',
    description: 'B2B SaaS company focused on developer tools',
    createdAt: '2024-01-15T10:00:00Z',
  },
  {
    id: 'brand-2',
    name: 'TradeWise',
    logo: '📈',
    description: 'Financial education and trading insights platform',
    createdAt: '2024-02-20T10:00:00Z',
  },
  {
    id: 'brand-3',
    name: 'FitLife Pro',
    logo: '💪',
    description: 'Health and fitness coaching brand',
    createdAt: '2024-03-10T10:00:00Z',
  },
];

export const mockCampaigns: Campaign[] = [
  // TechFlow Inc Campaigns
  {
    id: 'campaign-1',
    brandId: 'brand-1',
    name: 'AI Automation Launch',
    description: 'Product launch campaign for AI automation features',
    status: 'active',
    createdAt: '2024-09-01T10:00:00Z',
    updatedAt: '2024-11-15T10:00:00Z',
    settings: {
      searchKeywords: [
        'AI automation',
        'workflow automation',
        'no-code AI',
        'AI agents',
        'automation tools',
      ],
      creatorsToTrack: [
        {
          id: 'creator-1',
          name: 'Sarah Chen',
          platform: 'Twitter',
          handle: '@sarahchen_dev',
          addedAt: '2024-09-01T10:00:00Z',
        },
        {
          id: 'creator-2',
          name: 'TechCrunch',
          platform: 'Twitter',
          handle: '@TechCrunch',
          addedAt: '2024-09-01T10:00:00Z',
        },
        {
          id: 'creator-3',
          name: 'AI Explained',
          platform: 'YouTube',
          handle: '@aiexplained',
          addedAt: '2024-09-05T10:00:00Z',
        },
      ],
      platforms: ['Twitter', 'LinkedIn', 'YouTube'],
      brandVoice: 'Professional yet approachable. We demystify complex AI concepts and make automation accessible to everyone. Use analogies and real-world examples.',
      toneGuidelines: 'Educational, empowering, and forward-thinking. Avoid jargon unless explaining it. Be enthusiastic about possibilities without overhyping.',
      contentPillars: [
        'AI Education',
        'Automation Best Practices',
        'Product Updates',
        'Customer Success Stories',
        'Industry Trends',
      ],
      targetAudience: 'Tech-savvy professionals, developers, and business operators looking to streamline workflows',
      contentTypes: ['Tutorial', 'Tips & Tricks', 'Announcement', 'Case Study'],
      excludedTopics: ['Competitor criticism', 'Political content', 'Controversial AI ethics debates'],
      preferredPostingTimes: ['9:00 AM', '1:00 PM', '5:00 PM'],
      hashtagStrategy: 'Use 2-3 relevant hashtags. Focus on #AIAutomation #NoCode #ProductivityHacks',
    },
  },
  {
    id: 'campaign-2',
    brandId: 'brand-1',
    name: 'Developer Community Growth',
    description: 'Building and engaging with developer community',
    status: 'active',
    createdAt: '2024-10-01T10:00:00Z',
    updatedAt: '2024-11-15T10:00:00Z',
    settings: {
      searchKeywords: [
        'developer tools',
        'coding productivity',
        'API development',
        'DevOps',
        'software engineering',
      ],
      creatorsToTrack: [
        {
          id: 'creator-4',
          name: 'Theo - t3.gg',
          platform: 'Twitter',
          handle: '@t3dotgg',
          addedAt: '2024-10-01T10:00:00Z',
        },
        {
          id: 'creator-5',
          name: 'Fireship',
          platform: 'YouTube',
          handle: '@fireship',
          addedAt: '2024-10-01T10:00:00Z',
        },
      ],
      platforms: ['Twitter', 'Reddit', 'YouTube'],
      brandVoice: 'Casual, technical, and meme-aware. Speak like a fellow developer. Use code examples and developer humor.',
      toneGuidelines: 'Conversational and authentic. Embrace developer culture and inside jokes. Be helpful and supportive.',
      contentPillars: [
        'Coding Tips',
        'Tool Comparisons',
        'Developer Humor',
        'Open Source',
        'Tech News',
      ],
      targetAudience: 'Software developers, DevOps engineers, and tech enthusiasts',
      contentTypes: ['Tutorial', 'Tips & Tricks', 'News'],
      excludedTopics: ['Non-technical marketing speak', 'Overly corporate language'],
    },
  },
  
  // TradeWise Campaigns
  {
    id: 'campaign-3',
    brandId: 'brand-2',
    name: 'Q4 Trading Insights',
    description: 'Market analysis and trading education for Q4',
    status: 'active',
    createdAt: '2024-10-01T10:00:00Z',
    updatedAt: '2024-11-15T10:00:00Z',
    settings: {
      searchKeywords: [
        'stock market analysis',
        'trading strategies',
        'technical analysis',
        'market trends',
        'investment tips',
      ],
      creatorsToTrack: [
        {
          id: 'creator-6',
          name: 'Market Watch',
          platform: 'Twitter',
          handle: '@MarketWatch',
          addedAt: '2024-10-01T10:00:00Z',
        },
        {
          id: 'creator-7',
          name: 'Financial Times',
          platform: 'LinkedIn',
          handle: 'financial-times',
          addedAt: '2024-10-01T10:00:00Z',
        },
      ],
      platforms: ['Twitter', 'LinkedIn', 'YouTube'],
      brandVoice: 'Authoritative yet accessible financial expert. Balance data-driven insights with clear explanations. Build trust through transparency.',
      toneGuidelines: 'Professional, informative, and measured. Avoid hype and get-rich-quick language. Be realistic about risks.',
      contentPillars: [
        'Market Analysis',
        'Trading Education',
        'Risk Management',
        'Economic Trends',
        'Investment Strategies',
      ],
      targetAudience: 'Retail traders, investors, and finance professionals seeking actionable insights',
      contentTypes: ['Thought Leadership', 'News', 'Tutorial'],
      excludedTopics: ['Pump and dump schemes', 'Unverified tips', 'Financial advice (disclaimer required)'],
      hashtagStrategy: 'Use finance-specific hashtags: #Trading #StockMarket #FinancialEducation',
    },
  },
  {
    id: 'campaign-4',
    brandId: 'brand-2',
    name: 'Beginner Trader Onboarding',
    description: 'Educational content for new traders',
    status: 'active',
    createdAt: '2024-11-01T10:00:00Z',
    updatedAt: '2024-11-15T10:00:00Z',
    settings: {
      searchKeywords: [
        'beginner trading',
        'how to trade stocks',
        'trading basics',
        'investing for beginners',
      ],
      creatorsToTrack: [],
      platforms: ['YouTube', 'Blog', 'Twitter'],
      brandVoice: 'Patient teacher who breaks down complex concepts. Encouraging and supportive. Never condescending.',
      toneGuidelines: 'Clear, simple, and step-by-step. Use analogies. Celebrate small wins. Emphasize learning over quick profits.',
      contentPillars: [
        'Trading Basics',
        'Platform Tutorials',
        'Risk Management 101',
        'Common Mistakes',
        'Success Stories',
      ],
      targetAudience: 'Complete beginners with no trading experience',
      contentTypes: ['Tutorial', 'Tips & Tricks'],
      excludedTopics: ['Complex derivatives', 'Advanced strategies', 'Day trading hype'],
    },
  },

  // FitLife Pro Campaigns
  {
    id: 'campaign-5',
    brandId: 'brand-3',
    name: 'New Year Transformation',
    description: '2025 fitness transformation challenge',
    status: 'active',
    createdAt: '2024-11-01T10:00:00Z',
    updatedAt: '2024-11-15T10:00:00Z',
    settings: {
      searchKeywords: [
        'fitness transformation',
        'workout routine',
        'meal prep',
        'fitness motivation',
        'weight loss journey',
      ],
      creatorsToTrack: [
        {
          id: 'creator-8',
          name: 'Jeff Nippard',
          platform: 'YouTube',
          handle: '@jeffnippard',
          addedAt: '2024-11-01T10:00:00Z',
        },
      ],
      platforms: ['Twitter', 'LinkedIn', 'YouTube', 'Blog'],
      brandVoice: 'Motivational coach who champions sustainable fitness. Science-based but relatable. Celebrate progress over perfection.',
      toneGuidelines: 'Energetic, positive, and realistic. Avoid body-shaming or extreme rhetoric. Focus on health and strength.',
      contentPillars: [
        'Workout Plans',
        'Nutrition Advice',
        'Transformation Stories',
        'Fitness Science',
        'Mindset & Motivation',
      ],
      targetAudience: 'People looking to improve their fitness and adopt healthier lifestyles',
      contentTypes: ['Tutorial', 'Story', 'Tips & Tricks', 'Case Study'],
      excludedTopics: ['Extreme diets', 'Supplements without disclaimers', 'Body-shaming'],
      hashtagStrategy: '#FitnessJourney #HealthyLiving #TransformationTuesday #FitnessMotivation',
    },
  },
];
